
stages:
  - 🔨 build
  
# workflow:
#   rules:
#     - if: '$CI_COMMIT_BRANCH =~ "(master|develop|.*alpine)"'
#     - if: '$CI_COMMIT_BRANCH =~ "(master|develop|feature\/alpine)"'

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ThirdParty/

.build:linux:base:
  stage: 🔨 build
  image: alpine:3.14
  variables:
    BUILDDIR: "build"
    GIT_SUBMODULE_STRATEGY: recursive
    GRB_VERSION: "9.1.2"
    GRB_SHORT_VERSION: "9.1"
  before_script:
    # - apt-get update && apt-get install -y locales && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
    # - export LANG=en_US.utf8
    # - export DEBIAN_FRONTEND=noninteractive
    # - apt-get --no-install-recommends -y install gpg-agent software-properties-common dirmngr apt-transport-https lsb-release ca-certificates
    # - add-apt-repository -y ppa:ubuntu-toolchain-r/test
    # - apt-get --no-install-recommends -y install ${BB_CI_CC_COMPILER} ${BB_CI_CXX_COMPILER} clang-format libssl-dev git gcc g++ wget curl make ninja-build pkg-config python3 python3-pip tar unzip zip
    - apk add openssl git gcc g++ wget curl make pkgconf python3 py3-pip tar unzip zip
    - pip install -U cmake-format
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - wget https://packages.gurobi.com/${GRB_SHORT_VERSION}/gurobi${GRB_VERSION}_linux64.tar.gz
    - tar -xf gurobi${GRB_VERSION}_linux64.tar.gz
    - rm gurobi${GRB_VERSION}_linux64.tar.gz
    - mv gurobi* gurobi
    - mv gurobi /opt
    - export GUROBI_HOME=/opt/gurobi/linux64
    - ln -sf $GUROBI_HOME/lib/libgurobi_g++5.2.a $GUROBI_HOME/lib/libgurobi_c++.a
    - export LD_LIBRARY_PATH=$GUROBI_HOME/lib
    - ldconfig -v
    - chmod u+x before_script.sh
    - ./before_script.sh
  script:
    - mkdir -p ${BUILDDIR}
    - cmake -DCMAKE_C_COMPILER=${BB_CI_CC_COMPILER} -DCMAKE_CXX_COMPILER=${BB_CI_CXX_COMPILER} -DCMAKE_BUILD_TYPE=Release -B ${BUILDDIR} -S . -DCMAKE_TOOLCHAIN_FILE=./ThirdParty/vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmake --build ${BUILDDIR}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: "on_failure"
    paths:
      - ${BUILDDIR}/
    expire_in: 5 days


build:linux:gcc:
  extends: .build:linux:base
  variables:    
    BB_CI_CXX_COMPILER: "g++"
    BB_CI_CC_COMPILER: "gcc"

