
stages:
  - 🔨 build

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vcpkg/
    - ThirdParty/

.build:linux:base:
  stage: 🔨 build
  image: ubuntu:21.10
  variables:
    BUILDDIR: "build"
    GIT_SUBMODULE_STRATEGY: recursive
    GRB_VERSION: "9.1.2"
    GRB_SHORT_VERSION: "9.1"
  before_script:
    - apt-get update && apt-get install -y locales && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
    - export LANG=en_US.utf8
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get --no-install-recommends -y install gpg-agent software-properties-common dirmngr apt-transport-https lsb-release ca-certificates
    - add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - apt-get --no-install-recommends -y install ${BB_CI_CC_COMPILER} ${BB_CI_CXX_COMPILER} clang-format git gcc g++ cmake wget curl make ninja-build pkg-config python3 python3-pip tar unzip zip
    - pip install -U cmake-format
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - wget https://packages.gurobi.com/${GRB_SHORT_VERSION}/gurobi${GRB_VERSION}_linux64.tar.gz
    - tar -xf gurobi${GRB_VERSION}_linux64.tar.gz
    - rm gurobi${GRB_VERSION}_linux64.tar.gz
    - mv gurobi* gurobi
    - mv gurobi /opt
    - export GUROBI_HOME=/opt/gurobi/linux64
    - chmod u+x before_script.sh
    - ./before_script.sh
  script:
    - mkdir -p ${BUILDDIR}
    - CC=${BB_CI_CC_COMPILER} CXX=${BB_CI_CXX_COMPILER} cmake -B ${BUILDDIR} -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -CMAKE_BUILD_TYPE=Release
    - cmake --build ${BUILDDIR}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: "on_failure"
    paths:
      - ${BUILDDIR}/
      - vcpkg
      - ThirdParty
    expire_in: 5 days


build:linux:gcc:
  extends: .build:linux:base
  variables:    
    BB_CI_CXX_COMPILER: "g++-11"
    BB_CI_CC_COMPILER: "gcc-11"


build:linux:clang:
  extends: .build:linux:base
  variables:    
    BB_CI_CXX_COMPILER: "clang++-10"
    BB_CI_CC_COMPILER: "clang-10"



