
stages:
  - 🔨 build

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vcpkg/
    - ThirdParty/

.build:linux:base:
  stage: 🔨 build
  image: ubuntu:21.10
  variables:
    BUILDDIR: "build"
    GIT_SUBMODULE_STRATEGY: recursive
    GRB_VERSION: "9.1.2"
    GRB_SHORT_VERSION: "9.1"
  before_script:
    - apt-get update && apt-get install -y locales && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
    - export LANG=en_US.utf8
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get --no-install-recommends -y install gpg-agent software-properties-common dirmngr apt-transport-https lsb-release ca-certificates
    - add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - apt-get --no-install-recommends -y install ${BB_CI_CC_COMPILER} ${BB_CI_CXX_COMPILER} clang-format git gcc g++ cmake wget curl make ninja-build pkg-config python3 python3-pip tar unzip zip
    - pip install -U cmake-format
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - wget -v https://packages.gurobi.com/${GRB_SHORT_VERSION}/gurobi${GRB_VERSION}_linux64.tar.gz
    - tar -xvf gurobi${GRB_VERSION}_linux64.tar.gz
    - rm gurobi${GRB_VERSION}_linux64.tar.gz
    - mv gurobi* gurobi
    - mv gurobi /opt
    - export GUROBI_HOME=/opt/gurobi/linux64
    - mkdir ThirdParty
    - wget -O ThirdParty/coinbrew https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
    - chmod u+x ThirdParty/coinbrew
    - export CC=gcc-11
    - export CXX=g++-11
    - cd ThirdParty
    - ./coinbrew fetch Cgl@master
    - ./coinbrew build Cgl --no-prompt --prefix="./coin-or-x64-linux-release" --verbosity 4 --with-gurobi-lflags="-L$GUROBI_HOME/lib -lgurobi91 -lpthread -lm" --with-gurobi-cflags="-I$GUROBI_HOME/include" --tests none
    - ./coinbrew build Cgl --no-prompt --prefix="./coin-or-x64-linux-debug" --reconfigure --enable-debug --verbosity 4 --with-gurobi-lflags="-L$GUROBI_HOME/lib -lgurobi91 -lpthread -lm" --with-gurobi-cflags="-I$GUROBI_HOME/include" --tests none
    - cd ..
    - if [ ! -d vcpkg ] then git clone https://github.com/Microsoft/vcpkg.git && ./vcpkg/bootstrap-vcpkg.sh --useSystemBinaries && ./vcpkg/vcpkg install range-v3 fmt boost-chrono boost-timer boost-atomic boost-json boost-random boost-regex boost-serialization boost-multiprecision boost-graph docopt nlohmann-json
  script:
    - mkdir -p ${BUILDDIR}
    - CC=${BB_CI_CC_COMPILER} CXX=${BB_CI_CXX_COMPILER} cmake -B ${BUILDDIR} -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -CMAKE_BUILD_TYPE=Release
    - cmake --build ${BUILDDIR}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: "on_failure"
    paths:
      - ${BUILDDIR}/
      - vcpkg
    expire_in: 5 days


build:linux:gcc:
  extends: .build:linux:base
  variables:    
    BB_CI_CXX_COMPILER: "g++-11"
    BB_CI_CC_COMPILER: "gcc-11"


build:linux:clang:
  extends: .build:linux:base
  variables:    
    BB_CI_CXX_COMPILER: "clang++-10"
    BB_CI_CC_COMPILER: "clang-10"



